export const BLOG_ACTION_TYPES = {
  INITIAL_BLOG_FORM: "blog/INITIAL_BLOG_FORM",
  FETCH_BLOG_START: "blog/FETCH_BLOG_START",
  FETCH_BLOG_SUCCESS: "blog/FETCH_BLOG_SUCCESS",
  FETCH_BLOG_FAILED: "blog/FETCH_BLOG_FAILED",
  DELETE_BLOG_START: "blog/DELETE_BLOG_START",
  DELETE_BLOG_SUCCESS: "blog/DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAILED: "blog/DELETE_BLOG_FAILED",
  INSERT_BLOG_START: "blog/INSERT_BLOG_START",
  INSERT_BLOG_SUCCESS: "blog/INSERT_BLOG_SUCCESS",
  INSERT_BLOG_FAILED: "blog/INSERT_BLOG_FAILED",
};
